apiVersion: app/v1
kind: Deployment
metadata:
  namespace: test
  name: hr-web-app-sandeep
   labels:
    app: kodekloud/webapp-color
spec:
  replicas: 2
  labels:
    app: kodekloud/webapp-color
  containers:
  - name: sandeep-web-container
    image: kodekloud/webapp-color
  selector:
      app: kodekloud/webapp-color
  ports:
  - port: 3000
  

